// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// print_animal
void print_animal(SEXP animalSEXP);
RcppExport SEXP _AnimalCrossing_print_animal(SEXP animalSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type animalSEXP(animalSEXPSEXP);
    print_animal(animalSEXP);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_animal_module();

static const R_CallMethodDef CallEntries[] = {
    {"_AnimalCrossing_print_animal", (DL_FUNC) &_AnimalCrossing_print_animal, 1},
    {"_rcpp_module_boot_animal_module", (DL_FUNC) &_rcpp_module_boot_animal_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_AnimalCrossing(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
