# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Animal
#' @title Base Animal class
NULL

#' @name Duck
#' @title Duck class
#' @export
NULL

#' @name Dog
#' @title Dog class
#' @export
NULL

#' @name RAnimal
#' @title RAnimal generic class
#' @export
NULL

#' Print animal
#' @name print_animal
#' @param animalSEXP Duck, Dog, or RAnimal
#' @export
print_animal <- function(animalSEXP) {
    invisible(.Call(`_AnimalCrossing_print_animal`, animalSEXP))
}

#' @name CostBase
#' @title Base cost class
NULL

#' @name CostL2
#' @title L2 cost (fast, prefix sums)
#' @export
NULL

#' @name RCostClass
#' @title R-defined cost
#' @export
NULL

#' @name BinarySegmentation
#' @title Binary segmentation (single split)
#' @export
NULL

